Fix @import statements with variables
wikimedia/less.php pull request #33
Opened 2020-03-15 12:13 UTC by DemianX0

Fixes:
https://github.com/wikimedia/less.php/issues/32
https://github.com/oyejorge/less.php/issues/352

Merge from:
https://github.com/kylekatarnls/less.php/commit/e3d4aa4b5695000fa527b152656742a87afde9b1
https://github.com/kylekatarnls/less.php/commit/637fd9346cd72d4e277de9a263820d98867ec597

2020-03-15 12:30 UTC, MaxSem commented
No tests?

2020-03-18 01:53 UTC, Krinkle commented
It's not bad for compat, but in general, I think our system would remain easier to reason about if we don't allow variable imports. I'm not aware of a use case for it currently at WMF, and tends to cause hard-to-maintain or buggy code based on past experiences.

If we accept this, I would recommend that initially our LESS linter would disallow use of it in MW-related code.

2020-03-18 01:54 UTC, Krinkle commented
This is good for compat in general, but I think our system would remain easier to reason about if we don't allow variable imports. I'm not aware of a use case for it currently in MediaWiki, and such constructs tends to make for hard-to-maintain or buggy code based on past experiences.

If we accept this, I would recommend that initially our LESS linter would disallow use of it in MW-related code.

2020-03-18 02:41 UTC, DemianX0 commented
> I'm not aware of a use case for it currently in MediaWiki

Use-case:
https://gerrit.wikimedia.org/r/c/mediawiki/core/+/580558/3/resources/src/mediawiki.less/mediawiki.theme/variables.less

> I think our system would remain easier to reason about if we don't allow variable imports.

Variable imports are uncommon, so far nobody felt the need for it. The very few cases (1 now, probably for ever) can be done safely with good documentation. The explicit nature of this import and simplicity of LESS makes it easier to understand and reason about than a custom (proprietary) solution in ResourceLoader that potentially requires reading pages of PHP code to find.

> If we accept this, I would recommend that initially our LESS linter would disallow use of it in MW-related code.

Good idea. I don't think there'll be ever more than one usage of this LESS feature.

2020-03-18 03:04 UTC, Krinkle submitted a review, later dismissed
Holding back for now. The skin variable project is not yet on the annual roadmap. When it is, this will be considered as part of that.

2020-03-18 03:13 UTC, DemianX0 commented
> Holding back for now. The skin variable project is not yet on the annual roadmap. When it is, this will be considered as part of that.

I don't think such delay is necessary or beneficial. It takes away from the momentum.

2020-05-18 16:40 UTC, dleffler commented
Isn't this what is done with Twitter Bootstrap 3, especially with boot swatches?

2020-06-19 03:39 UTC, DemianX0 commented
> Isn't this what is done with Twitter Bootstrap 3, especially with boot swatches?

It could be used to parameterize which swatch to load.

2020-06-19 03:47 UTC, DemianX0 commented
> Holding back for now. The skin variable project is not yet on the annual roadmap. When it is, this will be considered as part of that.

This is a fix for a bug (incompatibility with less.js) that would benefit third party users as well.
It is also a prerequisite for my POC: https://gerrit.wikimedia.org/r/c/mediawiki/core/+/580558
which is one solution to https://phabricator.wikimedia.org/T112747 that the WMF failed to solve for 5 years.
I understand Krinkle does not like that solution, but that's not a technical concern, nor a reason to block demonstrating a solution.

After 3 months of nothing happening in these areas, do you wish to hold this up more, or can we consider making some actual improvement and doing some collaboration?

2020-09-18 20:07 UTC, Krinkle commented
> > Holding back for now. The skin variable project is not yet on the annual roadmap. When it is, this will be considered as part of that.
> 
> I don't think such delay is necessary or beneficial. It takes away from the momentum.

This isn't about the momentum of your change. There is an infinite number of things we can do that could theoretically be justified as useful for some people somewhere, that we could maybe even make use of in ourselves somewhere. But we're not going to do all of those things. The result would be useful things at the small scale, whilst getting nowhere as a community.

For every change, there is long-term cascading and repeating impact. Review, quality assurance, release - and repeat. For every new capability, there is more testing, documentation, future bug discovery, future maintenance, future migration and compatibility with other software and PHP versions, etc. It's not free.

We need to choose what's worthwhile investing in. And we need to invest with several people together. Going about uncoordinated in random directions on our own would mean you continuously have to drain and steal momentum from other projects in order to get something done. That means on average, there would be little to no momentum.

In the future, my recommendation is to focus your efforts on areas that you know have momemtum, or to first advocate or wait for an area to be on the roadmap. (In the case of "skin variables in MediaWiki", that's happening now, not last March).

I don't personally know the less.php code base well enough to be able to trivially review this as part of general maintenance, and I also can't justify spending days on getting familiar with it and shaping it because it turns out MW doesn't need this right now. Others or my future self might get around to this at some point, if they do, a test would surely help.

2021-05-03 23:19 UTC, Krinkle requested changes
Needs tests.

2021-07-09 18:55 UTC, closed without merging